### ISSUE TITLE
Import error with MultiQC module 

### ISSUE THREAD

**Issue by alexvcrr** [Gibbons-Lab/medi#19]
When running the next flow quant.nf script, an error occurs during the multiqc step. The error seems to be related to the version of the package typing.py. From what I found online the issue may be fixed by requiring Python >=3.9 in medi.yml (will test). See below for the error message.

Command error:
  Traceback (most recent call last):
    File "/users/acarr/anaconda3/envs/medi/bin/multiqc", line 6, in <module>
      from multiqc.__main__ import run_multiqc
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/multiqc/__init__.py", line 25, in <module>
      from multiqc import (  # noqa: E402
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/multiqc/report.py", line 42, in <module>
      from multiqc.base_module import BaseMultiqcModule, Section
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/multiqc/base_module.py", line 34, in <module>
      from multiqc import config, report, validation
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/multiqc/validation.py", line 10, in <module>
      from typeguard import TypeCheckError, check_type
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/typeguard/__init__.py", line 4, in <module>
      from ._checkers import TypeCheckerCallable as TypeCheckerCallable
    File "/users/acarr/anaconda3/envs/medi/lib/python3.8/site-packages/typeguard/_checkers.py", line 15, in <module>
      from typing import (
  ImportError: cannot import name 'Annotated' from 'typing' (/users/acarr/anaconda3/envs/medi/lib/python3.8/typing.py)

**Comment by alexvcrr** [comment]
Requiring Python >=3.9 in medi.yml results in failure to install the environment. Currently assessing if using older versions of  multiqc might fix the issue.

**Comment by alexvcrr** [comment]
Downgrading MultiQC to version 1.15 fixes the issues (suspect 1.16 is likely ok too)

**Comment by cdiener** [comment]
Yeah the pin is because of bracken 2.6 which only works with Python 3.8. Downgrading MultiQC definitely works. We could also try to update Bracken. But there was an issue with missing ranks. So we would need to test it first.

**Comment by cdiener** [comment]
Should be fixed now.
